# Generated by Django 5.2.5 on 2025-08-31 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='referred_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
