# Generated by Django 5.2.5 on 2025-08-31 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_userprofile_referred_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='points',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='referral_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
