# Generated by Django 5.2.5 on 2025-08-31 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_userprofile_points_userprofile_balance_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deposit',
            old_name='staus',
            new_name='status',
        ),
    ]
