# Generated by Django 5.2.5 on 2025-09-02 16:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_staus_deposit_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='ads_watched_today',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_ad_refresh',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=360, max_digits=10),
        ),
    ]
