# Generated by Django 5.2.5 on 2025-09-04 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_withdraw'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdraw',
            name='account_name',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
