# Generated by Django 5.2.5 on 2025-09-04 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_withdraw_account_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='bank_name',
            field=models.CharField(default='EasyPaisa', max_length=100),
        ),
        migrations.AddField(
            model_name='deposit',
            name='tracking_id',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
